version: '3.8'

services:
  api:
    container_name: TodoApi_Api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - api.env
    depends_on:
      - db
  db:
    container_name: TodoApi_db
    image:  "mcr.microsoft.com/mssql/server"
    hostname: sql-server
    ports:
      - "1433:1433"
    expose:
      - "1433"
    env_file: db.env
    volumes:
      - todo_data:/var/opt/mssql

volumes:
  todo_data: {}